'use client'

import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

// PDF Styles
const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottom: '1pt solid #e5e7eb',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: '#6b7280',
  },
  date: {
    fontSize: 10,
    color: '#9ca3af',
    marginBottom: 20,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    backgroundColor: '#f3f4f6',
    padding: 8,
    borderRadius: 4,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  statBox: {
    width: '30%',
    padding: 15,
    border: '1pt solid #e5e7eb',
    borderRadius: 4,
  },
  statTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  statValue: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  table: {
    display: 'flex',
    width: 'auto',
    marginTop: 10,
  },
  tableHeader: {
    backgroundColor: '#f9fafb',
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    borderBottomStyle: 'solid',
    alignItems: 'center',
    height: 40,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    borderBottomStyle: 'solid',
    alignItems: 'center',
    minHeight: 35,
  },
  tableCell: {
    padding: 8,
    fontSize: 10,
  },
  tableCellHeader: {
    padding: 8,
    fontSize: 10,
    fontWeight: 'bold',
  },
  colItem: {
    width: '30%',
  },
  colBranch: {
    width: '25%',
  },
  colQuantity: {
    width: '15%',
  },
  colReorder: {
    width: '15%',
  },
  colValue: {
    width: '15%',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    fontSize: 10,
    color: '#9ca3af',
    borderTop: '1pt solid #e5e7eb',
    paddingTop: 10,
  },
})

const formatCurrency = (value: number) =>
  new Intl.NumberFormat('en-US', { style: 'currency', currency: 'RWF', maximumFractionDigits: 0 }).format(value)

interface StockReportPDFProps {
  balances: any[]
  movementMap: Record<string, number>
  stockValue: number
  branchIdFilter?: string
  session: any
}

export function StockReportPDF({ 
  balances, 
  movementMap, 
  stockValue, 
  branchIdFilter,
  session 
}: StockReportPDFProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>DEVSLAB Inventory Report</Text>
          <Text style={styles.subtitle}>
            {branchIdFilter ? 'Branch Report' : 'Organization-wide Report'}
          </Text>
          <Text style={styles.date}>
            Generated on: {new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric',
              hour: '2-digit',
              minute: '2-digit'
            })}
          </Text>
          <Text style={styles.date}>
            Generated by: {session.user.name} ({session.user.role})
          </Text>
        </View>

        {/* Statistics */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Summary Statistics</Text>
          <View style={styles.statsContainer}>
            <View style={styles.statBox}>
              <Text style={styles.statTitle}>Stock Value</Text>
              <Text style={styles.statValue}>{formatCurrency(stockValue)}</Text>
            </View>
            <View style={styles.statBox}>
              <Text style={styles.statTitle}>Total Items</Text>
              <Text style={styles.statValue}>{balances.length}</Text>
            </View>
            <View style={styles.statBox}>
              <Text style={styles.statTitle}>Low Stock Items</Text>
              <Text style={[styles.statValue, { color: '#d97706' }]}>
                {balances.filter(b => b.quantity < b.item.reorderLevel).length}
              </Text>
            </View>
          </View>
        </View>

        {/* Movement Summary */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Movement Summary</Text>
          <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginTop: 10 }}>
            <View>
              <Text>Receives: {movementMap.RECEIVE || 0}</Text>
              <Text>Transfers: {movementMap.TRANSFER || 0}</Text>
            </View>
            <View>
              <Text>Issues: {movementMap.ISSUE || 0}</Text>
              <Text>Returns: {movementMap.RETURN || 0}</Text>
            </View>
            <View>
              <Text>Adjustments: {movementMap.ADJUST || 0}</Text>
              <Text>Disposals: {movementMap.DISPOSE || 0}</Text>
            </View>
          </View>
        </View>

        {/* Stock Balances Table */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Stock Balances</Text>
          <View style={styles.table}>
            {/* Table Header */}
            <View style={styles.tableHeader}>
              <Text style={[styles.tableCellHeader, styles.colItem]}>Item</Text>
              <Text style={[styles.tableCellHeader, styles.colBranch]}>Branch</Text>
              <Text style={[styles.tableCellHeader, styles.colQuantity]}>Quantity</Text>
              <Text style={[styles.tableCellHeader, styles.colReorder]}>Reorder Level</Text>
              <Text style={[styles.tableCellHeader, styles.colValue]}>Value</Text>
            </View>
            
            {/* Table Rows */}
            {balances.slice(0, 50).map((bal, index) => (
              <View key={bal.id} style={[
                styles.tableRow,
                { backgroundColor: index % 2 === 0 ? '#ffffff' : '#f9fafb' }
              ]}>
                <Text style={[styles.tableCell, styles.colItem]}>
                  {bal.item.name} ({bal.item.code})
                </Text>
                <Text style={[styles.tableCell, styles.colBranch]}>
                  {bal.branch?.name || 'N/A'}
                </Text>
                <Text style={[styles.tableCell, styles.colQuantity]}>
                  {bal.quantity}
                  {bal.quantity < bal.item.reorderLevel && (
                    <Text style={{ color: '#d97706', fontSize: 8 }}> (Low)</Text>
                  )}
                </Text>
                <Text style={[styles.tableCell, styles.colReorder]}>
                  {bal.item.reorderLevel}
                </Text>
                <Text style={[styles.tableCell, styles.colValue]}>
                  {formatCurrency((bal.item.currentPrice || 0) * bal.quantity)}
                </Text>
              </View>
            ))}
          </View>
          {balances.length === 0 && (
            <Text style={{ marginTop: 10, fontSize: 10, color: '#6b7280' }}>
              No stock balances available
            </Text>
          )}
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text>DEVSLAB LTD - Inventory Management System</Text>
          <Text>Page 1 of 1</Text>
        </View>
      </Page>
    </Document>
  )
}